name: saucectl espresso tests

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
        with:
          concurrency: 1

  cucumber-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run saucectl
        uses: saucelabs/saucectl-run-action@v4
        with:
          concurrency: 1
          working-directory: ./examples/cucumber
