apiVersion: v1alpha
kind: espresso
sauce:
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  # metadata:
  #   tags:
  #     - e2e
  #     - release team
  #     - other tag
  #   build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./apps/mda-1.0.10-12.apk
  testApp: ./apps/mda-androidTest-1.0.10-12.apk
suites:
  - name: "sauce labs Android Emulator poc"
    emulators:
      - name: "Android GoogleAPI Emulator"
        platformVersions:
          - "12.0"
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
